#!/bin/bash

echo "========================================="
echo "SLZA.SK Database Setup Guide"
echo "========================================="
echo ""
echo "Problem: DATABASE_URL ukazuje na localhost namiesto Supabase!"
echo ""
echo "RIEŠENIE:"
echo "1. Choď na: https://supabase.com/dashboard"
echo "2. Otvor svoj projekt"
echo "3. Choď do: Settings → Database"
echo "4. Nájdi sekciu 'Connection string'"
echo "5. Prepni na 'Transaction Mode' alebo 'Session Mode'"
echo "6. Skopíruj connection string"
echo "7. Nahraď [YOUR-PASSWORD] skutočným heslom"
echo ""
echo "8. Uprav .env.local:"
echo "   DATABASE_URL=\"postgresql://postgres.xxxxx:[PASSWORD]@aws-0-eu-central-1.pooler.supabase.com:6543/postgres\""
echo ""
echo "9. Tiež pridaj OWNCLOUD_ROOT (chýba):"
echo "   OWNCLOUD_ROOT=\"/tlacove_podklady\""
echo ""
echo "10. Spusti migrácie:"
echo "    cd frontend && npx prisma migrate deploy"
echo ""
echo "11. Vytvor admin účet:"
echo "    npx ts-node scripts/create-admin.ts"
echo ""
echo "========================================="
